library(tidyverse)
library(furrr)
library(tictoc)
library(tidymodels)
library(survival)
library(survminer)
library(glmnet)
library(granatlib)
# c("price_diff", "offer_price", "fair_price", names(cars_data), names(accessories_df)) %>%
# walk(print)

NiceName <- function(x, .rmTRUE = TRUE) {
  if (.rmTRUE) {
    x <- str_remove(x, "TRUE")
  }
  
  case_when(
    x == "price_diff" ~ x,
    x == "offer_price" ~ x,
    x == "fair_price" ~ x,
    x == "id" ~ x,
    x == "brand" ~ x,
    x == "evjarat" ~ "year of manufacture",
    x == "allapot" ~ "condition",
    x == "kivitel" ~ "design", # TODO
    x == "kilometerora_allasa" ~ "mileage",
    x == "szallithato_szem_szama" ~ "number of persons transported",
    x == "ajtok_szama" ~ "number of doors",
    x == "klima_fajtaja" ~ "type of climate",
    x == "uzemanyag" ~ "type of fuel",
    x == "hengerurtartalom" ~ "cylinder capacity",
    x == "teljesitmeny" ~ "engine performance",
    x == "henger_elrendezes" ~ "cylinder layout",
    x == "hajtas" ~ "wheel drive", # TODO
    x == "sebessegvalto_fajtaja" ~ "type of gear",
    x == "muszaki_vizsga_ervenyes" ~ "valid MOT",
    x == "nyari_gumi_meret" ~ "tire size 1",
    x == "szin" ~ "color",
    x == "sajat_tomeg" ~ "own weight",
    x == "teljes_tomeg" ~ "total weight",
    x == "csomagtarto" ~ "trunk",
    x == "nyari_gumi_meret2" ~ "tire size 2",
    x == "nyari_gumi_meret3" ~ "tire size 3",
    x == "sebessegvalto_fokozatszam" ~ "number of breaks on the gear",
    x == "id" ~ x,
    x == "dontheto_utasulesek" ~ x,
    x == "pluss_karpit" ~ x,
    x == "ulesmagassag_allitas" ~ x,
    x == "kozepso_kartamasz" ~ x,
    x == "multifunkcios_kormanykerek" ~ x,
    x == "velur_karpit" ~ x,
    x == "fuggonylegzsak" ~ x,
    x == "isofix_rendszer" ~ x,
    x == "kikapcsolhato_legzsak" ~ x,
    x == "oldallegzsak" ~ x,
    x == "utasoldali_legzsak" ~ x,
    x == "vezetooldali_legzsak" ~ x,
    x == "hatso_fejtamlak" ~ x,
    x == "allithato_kormany" ~ x,
    x == "fedelzeti_komputer" ~ x,
    x == "tavolsagi_fenyszoro_asszisztens" ~ x,
    x == "abs_blokkolasgatlo" ~ x,
    x == "esp_menetstabilizator" ~ x,
    x == "ebd_ebv_elektronikus_fekero_eloszto" ~ x,
    x == "savtarto_rendszer" ~ x,
    x == "tabla_felismero_funkcio" ~ x,
    x == "guminyomas_ellenorzo_rendszer" ~ x,
    x == "inditasgatlo_immobiliser" ~ x,
    x == "savvalto_asszisztens" ~ x,
    x == "visszagurulas_gatlo" ~ x,
    x == "lejtmenet_asszisztens" ~ x,
    x == "fekasszisztens" ~ x,
    x == "centralzar" ~ x,
    x == "riaszto" ~ x,
    x == "szervokormany" ~ x,
    x == "tempomat" ~ x,
    x == "sebessegfuggo_szervokormany" ~ x,
    x == "elektromosan_behajthato_kulso_tukrok" ~ x,
    x == "fenyszoro_magassagallitas" ~ x,
    x == "elektromos_ablak_elol" ~ x,
    x == "elektromos_ablak_hatul" ~ x,
    x == "elektromos_tukor" ~ x,
    x == "futheto_tukor" ~ x,
    x == "konnyufem_felni" ~ x,
    x == "szinezett_uveg" ~ x,
    x == "defektjavito_keszlet" ~ x,
    x == "bluetooth_os_kihangosito" ~ x,
    x == "i_phone_i_pod_csatlakozo" ~ x,
    x == "usb_csatlakozo" ~ x,
    x == "tolatokamera_bemenet" ~ x,
    x == "erintokijelzo" ~ x,
    x == "hangszoro" ~ x,
    x == "autobeszamitas_lehetseges" ~ x,
    x == "elso_forgalomba_helyezes_magyarorszagon" ~ x,
    x == "garancialis" ~ x,
    x == "rendelheto" ~ x,
    x == "torzskonyv" ~ x,
    x == "vezetett_szervizkonyv" ~ x,
    x == "allithato_hatso_ulesek" ~ x,
    x == "tolatoradar" ~ x,
    x == "asr_kiporgesgatlo" ~ x,
    x == "kodlampa" ~ x,
    x == "esoszenzor" ~ x,
    x == "led_fenyszoro" ~ x,
    x == "aux_csatlakozo" ~ x,
    x == "mp3_lejatszas" ~ x,
    x == "mp4_lejatszas" ~ x,
    x == "hifi" ~ x,
    x == "futheto_elso_ules" ~ x,
    x == "radio" ~ x,
    x == "bor_belso" ~ x,
    x == "faberakas" ~ x,
    x == "automatikusan_sotetedo_belso_tukor" ~ x,
    x == "elektromos_ulesallitas_vezetooldal" ~ x,
    x == "elektromos_ulesallitas_utasoldal" ~ x,
    x == "reszecskeszuro" ~ x,
    x == "kulcsnelkuli_inditas" ~ x,
    x == "automatikusan_sotetedo_kulso_tukor" ~ x,
    x == "gps_navigacio" ~ x,
    x == "dvb_t_tuner" ~ x,
    x == "azonnal_elviheto" ~ x,
    x == "hutheto_kesztyutarto" ~ x,
    x == "allithato_combtamasz" ~ x,
    x == "derektamasz" ~ x,
    x == "bor_szovet_huzat" ~ x,
    x == "hatso_oldal_legzsak" ~ x,
    x == "kormanyvalto" ~ x,
    x == "ard_automatikus_tavolsagtarto" ~ x,
    x == "futoszalas_szelvedo" ~ x,
    x == "kanyarkoveto_fenyszoro" ~ x,
    x == "kihangosito" ~ x,
    x == "x8_hangszoro" ~ x,
    x == "tolatokamera" ~ x,
    x == "tavolsagtarto_tempomat" ~ x,
    x == "potkerek" ~ x,
    x == "bemutato_jarmu" ~ x,
    x == "x4_hangszoro" ~ x,
    x == "futheto_kormany" ~ x,
    x == "holtter_figyelo_rendszer" ~ x,
    x == "fenyszoromoso" ~ x,
    x == "keramia_fektarcsak" ~ x,
    x == "toloajto" ~ x,
    x == "terdlegzsak" ~ x,
    x == "kiegeszito_fenyszoro" ~ x,
    x == "memoriakartya_olvaso" ~ x,
    x == "erosito_kimenet" ~ x,
    x == "mikrofon_bemenet" ~ x,
    x == "erosito" ~ x,
    x == "gyari_erosito" ~ x,
    x == "x2_din" ~ x,
    x == "sportulesek" ~ x,
    x == "krom_felni" ~ x,
    x == "csomag_rogzito" ~ x,
    x == "sportfutomu" ~ x,
    x == "memorias_vezetoules" ~ x,
    x == "ads_adaptiv_lengescsillapito" ~ x,
    x == "allithato_felfuggesztes" ~ x,
    x == "elektromos_csomagterajto_mozgatas" ~ x,
    x == "toloteto_napfenyteto" ~ x,
    x == "toloteto_elektromos" ~ x,
    x == "sebessegvalto_zar" ~ x,
    x == "vonohorog" ~ x,
    x == "elso_tulajdonostol" ~ x,
    x == "keveset_futott" ~ x,
    x == "nem_dohanyzo" ~ x,
    x == "rendszeresen_karbantartott" ~ x,
    x == "dokumentumok" ~ x,
    x == "x230v_csatlakozo_hatul" ~ x,
    x == "x360_fokos_kamerarendszer" ~ x,
    x == "elso_hatso_parkoloradar" ~ x,
    x == "start_stop_motormegallito_rendszer" ~ x,
    x == "cd_s_autoradio" ~ x,
    x == "garantalt_km_futas" ~ x,
    x == "masodik_tulajdonostol" ~ x,
    x == "garazsban_tartott" ~ x,
    x == "holgy_tulajdonostol" ~ x,
    x == "hangvezerles" ~ x,
    x == "frissen_szervizelt" ~ x,
    x == "cd_tar" ~ x,
    x == "uleshutes_szelloztetes" ~ x,
    x == "xenon_fenyszoro" ~ x,
    x == "edc_elektronikus_lengescsillapitas_vezerles" ~ x,
    x == "masszirozos_ules" ~ x,
    x == "merevlemez" ~ x,
    x == "borkormany" ~ x,
    x == "digitalis_muszeregyseg" ~ x,
    x == "hud_head_up_display" ~ x,
    x == "kulcsnelkuli_nyitorendszer" ~ x,
    x == "elektronikus_rogzitofek" ~ x,
    x == "utkozes_veszelyre_felkeszito_rendszer" ~ x,
    x == "faradtsagerzekelo" ~ x,
    x == "veszfek_asszisztens" ~ x,
    x == "automata_fenyszorokapcsolas" ~ x,
    x == "automata_tavfeny" ~ x,
    x == "menetfeny" ~ x,
    x == "bukolampa" ~ x,
    x == "led_matrix_fenyszoro" ~ x,
    x == "android_auto" ~ x,
    x == "apple_car_play" ~ x,
    x == "kormanyrol_vezerelheto_hifi" ~ x,
    x == "multifunkcionalis_kijelzo" ~ x,
    x == "gps_nyomkoveto" ~ x,
    x == "x7_hangszoro" ~ x,
    x == "mubor_karpit" ~ x,
    x == "futheto_ablakmoso_fuvokak" ~ x,
    x == "elektronikus_futomu_hangolas" ~ x,
    x == "autotelefon" ~ x,
    x == "x10_hangszoro" ~ x,
    x == "dvd" ~ x,
    x == "x12_hangszoro" ~ x,
    x == "ajtoszervo" ~ x,
    x == "defektturo_abroncsok" ~ x,
    x == "allofutes" ~ x,
    x == "eds_elektronikus_differencialzar" ~ x,
    x == "memorias_utasules" ~ x,
    x == "futheto_elso_es_hatso_ulesek" ~ x,
    x == "vezetek_nelkuli_telefontoltes" ~ x,
    x == "motorbeszamitas_lehetseges" ~ x,
    x == "full_extra" ~ x,
    x == "hutheto_kartamasz" ~ x,
    x == "elektromosan_allithato_fejtamlak" ~ x,
    x == "wma_lejatszas" ~ x,
    x == "msr_motorfeknyomatek_szabalyzas" ~ x,
    x == "bi_xenon_fenyszoro" ~ x,
    x == "sperr_differencialmu" ~ x,
    x == "radaros_fekasszisztens" ~ x,
    x == "afa_visszaigenyelheto" ~ x,
    x == "gyalogos_legzsak" ~ x,
    x == "automatikus_segelyhivo" ~ x,
    x == "parkoloasszisztens" ~ x,
    x == "x9_hangszoro" ~ x,
    x == "tv" ~ x,
    x == "automatikus_hengerlekapcsolas" ~ x,
    x == "rablasgatlo" ~ x,
    x == "melynyomo" ~ x,
    x == "vonohorog_elektromosan_kihajthato" ~ x,
    x == "bekanyarodasi_segedfeny" ~ x,
    x == "ejjellato_asszisztens" ~ x,
    x == "garazsajto_taviranyito" ~ x,
    x == "hatso_keresztiranyu_forgalomra_figyelmeztetes" ~ x,
    x == "koccanasgatlo" ~ x,
    x == "alcantara_karpit" ~ x,
    x == "dvb_tuner" ~ x,
    x == "allo_helyzeti_klima" ~ x,
    x == "type2_toltokabel" ~ x,
    x == "otthoni_halozati_tolto" ~ x,
    x == "gesztusvezerles" ~ x,
    x == "hdmi_bemenet" ~ x,
    x == "radios_magno" ~ x,
    x == "fejtamlamonitor" ~ x,
    x == "hud_head_up_display_kiterjesztett_valosag_funkcioval" ~ x,
    x == "wi_fi_hotspot" ~ x,
    x == "x1_din" ~ x,
    x == "x2_hangszoro" ~ x,
    x == "tetocsomagtarto" ~ x,
    x == "taviranyito" ~ x,
    x == "ketoldali_toloajto" ~ x,
    x == "mozgasserult" ~ x,
    x == "x5_hangszoro" ~ x,
    x == "kozepso_legzsak_elol" ~ x,
    x == "fm_transzmitter" ~ x,
    x == "kormanyra_szerelheto_taviranyito" ~ x,
    x == "vonohorog_leveheto_fejjel" ~ x,
    x == "chiptuning" ~ x,
    x == "jobbkormanyos" ~ x,
    x == "analog_tv_tuner" ~ x,
    x == "bukocso" ~ x,
    x == "amerikai_modell" ~ x,
    x == "beepitett_gyerekules" ~ x,
    x == "x11_hangszoro" ~ x,
    x == "taxi" ~ x,
    x == "bekanyarodasi_asszisztens" ~ x,
    x == "x4ws_osszkerekkormanyzas" ~ x,
    x == "taviranyitassal_ledontheto_hatso_ulestamla" ~ x,
    x == "tetomonitor" ~ x,
    x == "pot_uzemanyagtartaly" ~ x,
    x == "tetore_szerelheto_kerekpartarto" ~ x,
    x == "vonohorgos_kerekpartarto" ~ x,
    x == "vegig_vezetett_szervizkonyv" ~ x,
    x == "kulcsnelkuli_nyitorendszer_2" ~ x,
    TRUE ~ x
  )
}
